# Generated by Django 3.2.8 on 2021-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sap_insumo', models.IntegerField(unique=True)),
                ('descricao_insumo', models.CharField(max_length=150)),
            ],
        ),
    ]
