# Generated by Django 3.2.8 on 2021-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroproduto',
            options={'verbose_name': 'Cadastro de Produto', 'verbose_name_plural': 'Cadastro de Produtos'},
        ),
        migrations.AddField(
            model_name='cadastroproduto',
            name='descricao_produto',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cadastroproduto',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cadastroproduto',
            name='utilizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
